FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /bin/app-log-writer ./services/log-writer/cmd

FROM alpine:3.20
RUN apk add --no-cache ca-certificates postgresql16-client
COPY --from=builder /bin/app-log-writer /bin/app-log-writer
ENTRYPOINT ["/bin/app-log-writer"]
