---

- name: Deploy etcd cluster
  hosts: etcd_nodes
  become: true
  roles:
    - etcd

- name: Deploy PostgreSQL primary
  hosts: pg-primary
  become: true
  roles:
    - postgresql
    - node-agent

- name: Deploy PostgreSQL replicas
  hosts: pg_nodes:!pg-primary
  become: true
  roles:
    - postgresql
    - node-agent

- name: Deploy HA Orchestrator
  hosts: orchestrator
  become: true
  roles:
    - orchestrator

- name: Deploy HAProxy
  hosts: haproxy
  become: true
  roles:
    - haproxy
